# Generated by Django 5.0.6 on 2024-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='horaFin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='horaInicio',
            field=models.DateField(null=True),
        ),
    ]
