# Generated by Django 5.0.6 on 2024-07-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocrud', '0002_horarios_horafin_horarios_horainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='horaFin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='horaInicio',
            field=models.DateTimeField(null=True),
        ),
    ]
